-- Auto-generated by Pylutus Forge
{-# INLINABLE mkValidator #-}
import PlutusTx.Prelude
import Plutus.V1.Ledger.Api
mkValidator :: Datum -> Redeemer -> ScriptContext -> Bool
mkValidator datum redeemer ctx =
    if datum == "escrow" && redeemer == "release" then (
        traceIfFalse "Payment failed" (checkPayment ctx PubKeyHash "abc123" 2000000)
        traceIfFalse "Return" True
        traceIfFalse "Valid" True
    ) else (
        traceIfFalse "Invalid" False
    )

checkPayment :: ScriptContext -> PubKeyHash -> Integer -> Bool
checkPayment ctx pkh amount =
    any (\o -> txOutValue o == lovelaceValueOf amount && txOutAddress o == pubKeyHashAddress pkh) (txInfoOutputs $ scriptContextTxInfo ctx)